### ISSUE TITLE
[Feature] minimum support

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#1]
First goal is minimu support.
## Features
- `__init__`  in `pydantic.BaseModel`
- `__init__` in `pydantic.dataclasses.dataclass`

## Related issue
https://github.com/samuelcolvin/pydantic/issues/650

**Comment by MrMrRobat** [comment]
This is awesome, thanks much!

Just installed it and don't have any issues with `BaseModel.__init__`  yet. auto completion works, type warnings raised properly.

But unfortunately it marks every attribute as unexpected when dealing with dataclasses: 
Is there a way to temporary disable inspection for dataclasses until it gets implemented properly?

![image](https://user-images.githubusercontent.com/36469655/62465250-1e6e4a80-b797-11e9-922a-25b0f66ab47f.png)

**Comment by koxudaxi** [comment]
@MrMrRobat 
Thank you for your response!!
I have understood the problem of dataclass.

> Is there a way to temporary disable inspection for dataclasses until it gets implemented properly?

Sorry, I don't have the way.
I'm developing [code generator for pydantic](https://github.com/koxudaxi/datamodel-code-generator). If I implement the essential features of the code generator, then I will fix the plugin.
I want to do it this week.

**Comment by MrMrRobat** [comment]
No problem :+1: 

> I'm developing [code generator for pydantic](https://github.com/koxudaxi/datamodel-code-generator).

Thanks for sharing, seems like another great project is in development! Good luck with the features.

**Comment by MrMrRobat** [comment]
Wow, actually it's breaking not only `pydantic.dataclasses` inspections. Some other classes broken now, include Exceptions and more. :crying_cat_face: 
![image](https://user-images.githubusercontent.com/36469655/62469238-86755e80-b7a0-11e9-92d4-6223ef8b7df3.png)

**Comment by koxudaxi** [comment]
@MrMrRobat 
Oh, Sorry 😢 
Thank you for your notification.
I will check the code next time.

**Comment by koxudaxi** [comment]
@MrMrRobat
I fix the bugs.
Please check screen shots.
And upload plugin as version 0.0.2

<img width="445" alt="ss2019-08-08 2 47 48" src="https://user-images.githubusercontent.com/630670/62645354-03622d00-b987-11e9-88bb-e549ac833060.png">
<img width="582" alt="ss2019-08-08 2 43 55" src="https://user-images.githubusercontent.com/630670/62645355-03622d00-b987-11e9-9d71-4247cebb55ed.png">

**Comment by dmontagu** [comment]
This is great! So glad you shared this!

**Comment by MrMrRobat** [comment]
Thanks much, installing 0.0.3 right now :smile:

**Comment by koxudaxi** [comment]
Latest version 0.0.14 supports `pydantic.dataclasses.dataclass`
It's first goal.
