### ISSUE TITLE
Proper description keyword parsing 

### ISSUE THREAD

**Issue by thepowerfuldeez** [koxudaxi/pydantic-pycharm-plugin#111]
Hi! Thank you for your great plugin! I've noticed that when you have description keyword filled in BaseModel pydantic class then autocompletion shows me that parameter in hints. See screenshot
![image](https://user-images.githubusercontent.com/11796343/80280182-344be300-870b-11ea-9b5c-1d7d8f2a57ba.png)

**Comment by koxudaxi** [comment]
@thepowerfuldeez 
Thank you for creating this issue.
Sorry, I couldn't confirm your problem.
Could you please show me your code and your plugin version?

```python
from pydantic import BaseModel, Field


class Foobar(BaseModel):
    url: str = Field('xyz', description='efg')
    description: str = '123'


f = Foobar(url='abc')
```
![Screenshot_2020-04-26_19-07-06](https://user-images.githubusercontent.com/630670/80304509-53bd3b80-87f1-11ea-8a86-938a44d393ee.png)

**Comment by koxudaxi** [comment]
No response.
