### ISSUE TITLE
Wrong behaviour with allow_population_by_field_name 

### ISSUE THREAD

**Issue by spacemanspiff2007** [koxudaxi/pydantic-pycharm-plugin#112]
```py
from typing import Dict, Any

from pydantic import BaseConfig, BaseModel, Extra, Field

BaseConfig.extra = Extra.forbid
BaseConfig.allow_population_by_field_name = True

class ItemChannelLinkDefinition(BaseModel):
    item_name: str = Field(alias='itemName')
    configuration: Dict[str, Any] = {}


ItemChannelLinkDefinition(item_name='asdf')
```

The Config switch ``allow_population_by_field_name`` means that it's allowed to use the field name in the constructor. 
Unfortunately the plugin shows an error.

![grafik](https://user-images.githubusercontent.com/10754716/80270938-aea14680-86bc-11ea-8ba7-8a6d6adb9599.png)

**Comment by koxudaxi** [comment]
@spacemanspiff2007 
Thank you for creating this issue.
I understand why you get the warning.
The plugin expects a Config is an inner class in Model.
However, you assign config values to Config on modules.
I will try to fix it.
Thank you.

![Screenshot_2020-04-26_19-19-41](https://user-images.githubusercontent.com/630670/80304734-eb6f5980-87f2-11ea-9799-7b86fa36c80b.png)

**Comment by samuelcolvin** [comment]
I would argue that messing with `BaseConfig` was a mistake anyway. It's not suggested anywhere in the docs.

**Comment by koxudaxi** [comment]
@samuelcolvin 

Thank you for your comment.
OK, I understand And, I have removed `bug` tag.
Also, It's difficult to check BaseConfig is changed on PyCharm.

**Comment by spacemanspiff2007** [comment]
> I would argue that messing with BaseConfig was a mistake anyway. It's not suggested anywhere in the docs.

How would I change the config for all Models then?

**Comment by samuelcolvin** [comment]
Use a shared custom base model with its own config.

**Comment by koxudaxi** [comment]
Thank you for your answer.
I close this issue.
