### ISSUE TITLE
InitVar support for dataclasses

### ISSUE THREAD

**Issue by nsidnev** [koxudaxi/pydantic-pycharm-plugin#147]
Hi! Thanks for your plugin, it is really very useful when using `pydantic`.

I use `dataclasses` from `pydantic`, and in some of my classes I use fields declared using `InitVar` typing to mark them as init-only for later use in `__post_init__`. This plugin currently understands that the field should only be used for initialization.
and when I try to use it as an attribute of an object, it says about an error, but it doesn’t understand that instead of `InitVar[int]`, you can use `int` and there should be no error.

Hope this is not very difficult to fix. Thanks!
![image](https://user-images.githubusercontent.com/22559461/84152002-c82fff00-aa6c-11ea-8e9c-eb4fbe0fe2df.png)

**Comment by koxudaxi** [comment]
@nsidnev 
Thank you for creating this issue.

I try your code in my PyCharm.
But, The error doesn't appear.
![Screenshot_2020-06-10_01-40-30](https://user-images.githubusercontent.com/630670/84175981-b0cc3280-aabb-11ea-8471-2981c6536769.png)

Would you please tell me this information on your environment?
- Python version
- PyCharm version
- Pydantic Plugin version

PyCharm 2020.1.x and Pydantic plugin version 0.1.0 or later support pydantic.dataclasses.

**Comment by nsidnev** [comment]
Oh, it's my fault, I'm sorry. For some reason, PyCharm didn't tell me (or somehow I missed it) that the plugin had an update.
After updating the plugin, everything works perfectly!

Thanks again!
