### ISSUE TITLE
Feature request: Refactoring to rename a model attribute changes the name in initializers

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#16]
This would bring it in-line with how doing a refactor on the `__init__` signature works for normal classes. I could imagine this being hard to accomplish, in which case it may not be worth it, but it would be a *very* nice capability to have.

Neither the attrs nor dataclass plugins support this now, so it's by no means a need-to-have, but that didn't stop you from solving #4 ! And again, I think it would be very useful!

-----
More concretely, right now, when you do a refactor, you go from this:

![Screen Shot 2019-08-09 at 11 39 48 AM](https://user-images.githubusercontent.com/35119617/62801426-8c1dbd80-ba9a-11e9-8655-c87e77f3f945.png)

to this:

![Screen Shot 2019-08-09 at 11 39 54 AM](https://user-images.githubusercontent.com/35119617/62801430-8fb14480-ba9a-11e9-8c14-3063a4e301f1.png)

**I would like it to instead go to this:**

![Screen Shot 2019-08-09 at 11 43 08 AM](https://user-images.githubusercontent.com/35119617/62801464-a3f54180-ba9a-11e9-8b2a-810b83772221.png)

**Comment by dmontagu** [comment]
Note: the screenshots show an error in the `get_modified_model` call because I hadn't updated to 0.0.8, which solves the problem causing that. But I have confirmed that this issue still applies to 0.0.8.

**Comment by dmontagu** [comment]
Also, here is the code screenshotted above (with a minor linting fix) in case you want to just copy it:
```python
from pydantic import BaseModel


class Model(BaseModel):
    number: int


def get_modified_model(model_: Model) -> Model:
    return Model(number=2 * model_.number)


model = Model(number=1)
modified_model = get_modified_model(model)
```

**Comment by koxudaxi** [comment]
I'm very interested in.
However, I should learn the code of IntelliJ. 
I will try it.

> Neither the attrs nor dataclass plugins support this now

Oh, Really? we need this feature 😢

**Comment by dmontagu** [comment]
@koxudaxi I did a tiny bit of digging, I think this might be helpful: https://intellij-support.jetbrains.com/hc/en-us/community/posts/206768825-Refactor-Listener

**Comment by koxudaxi** [comment]
@dmontagu 
Thank you for giving me a useful link.
I have implemented the refactoring field name feature.
## Refacor dialog
<img width="593" alt="ss2019-08-12 4 55 24" src="https://user-images.githubusercontent.com/630670/62838988-82749f80-bcbe-11e9-860c-f5f35764b6dc.png">
## Result
<img width="550" alt="ss2019-08-12 4 55 33" src="https://user-images.githubusercontent.com/630670/62838989-86082680-bcbe-11e9-9753-cacdf630ac30.png">

The feature supports only one way. if you change filed names then, the plugin rewrites keyword arguments.
However, the reverse way doesn't work.
I can't resolve a class name from  constructor of`BaseModel`

**Comment by dmontagu** [comment]
@koxudaxi Maybe there is a minor modification to pydantic that could enable this. I'll think about it.

I tested it out, and it looks like this doesn't work with pydantic dataclasses. I think that's not that big of a deal, but it also wouldn't surprise me if it were easy to enable since you figured it out for BaseModel. Thoughts?

**Comment by dmontagu** [comment]
@koxudaxi any chance you could share the attempted implementation going in the other direction (that doesn't work)? I would like to play with it a bit, but I don't even know where to begin.

For what it's worth, I think this is still super useful as is (at least now it is *possible* to refactor safely). But it would be nice if you didn't have to remember to do it the "safe" way.

**Comment by koxudaxi** [comment]
@dmontagu 
Thank you.  I may write some code to able to detect as a contractor in the plugin.    

Yes, I have not written it for dataclass yet. I think I should work for `BaseModel` first.
We can watch source code for python's dataclass in IntelliJ repository.
I know it's easy to support pydantic's dataclass, but we spend time ...

**Comment by dmontagu** [comment]
Yes, I think that's right. I personally never use `pydantic.dataclasses.dataclass`, but there are enough issues about it on the pydantic github that it seems worth supporting (eventually).

Regardless, I think this plugin is already useful enough (and bug-free enough) to be worth 1) including in the PyCharm plugin store, and 2) including somewhere in the pydantic docs.

Thank you for all your effort on this!!

**Comment by koxudaxi** [comment]
> you could share the attempted implementation going in the other direction (that doesn't work)?

Did you tell ask about the implementation?

> I can't resolve a class name from constructor of `BaseModel`

Sorry, I don't have another code, I always push it to this repository.
I often breakpoint and interactive eval in IntelliJ.
It's required to understand IntelliJ modules.

**Comment by dmontagu** [comment]
@koxudaxi  No problem. Is there a way to try out modifications that doesn't involve building, installing into PyCharm, restarting PyCharm, and seeing if it worked?

**Comment by koxudaxi** [comment]
Regardless, I think this plugin is already useful enough (and bug-free enough) to be worth 1) including in the PyCharm plugin store (or whatever it is called), and 2) including somewhere in the pydantic docs.

OK, I will do it 👍

**Comment by dmontagu** [comment]
I loaded the project in IDEA, now I can see all the relevant JetBrains classes. I have barely any java/kotlin experience, but I'll play with it 😅

**Comment by dmontagu** [comment]
@koxudaxi do you know which method/classes are involved if you do a rename where you try to change the name from inside the `__init__` call? (The "reverse way" as you called it above)

**Comment by koxudaxi** [comment]
I have written how to build and run in README 
`$ ./gradlew runIde`
It's very easy, the build script starts up new PyCharm for a test.
Or, you should do sets for running plugin

**Comment by koxudaxi** [comment]
@dmontagu 
I think the method detects element for refactoring  code
https://github.com/koxudaxi/pydantic-pycharm-plugin/blob/46d660c5a2ab9564fcd858850c14674d2f6c52a5/src/com/koxudaxi/pydantic/PydanticFieldRenameFactory.kt#L19

**Comment by koxudaxi** [comment]
I thought java program is strict. but, the code like beautiful soup 4.
We have to cast or check type. It's too dynamic.

I can get `PyKeywordArgument` when calling a constructor of `BaseModel`, but the object doesn't have class information.
However, I call a constructor of python's `object`, it returns `PyParameter` has class information 😢

**Comment by dmontagu** [comment]
I'm going to close this and open a more specific issue, given this now works.
