### ISSUE TITLE
Plugin's features for Pydantic dynamic models

### ISSUE THREAD

**Issue by bukosabino** [koxudaxi/pydantic-pycharm-plugin#169]
Hi @koxudaxi ,

Congratulations on your work on this plugin. I am using to inspect and autocomplete Pydantic models on Pycharm, and it works like a charm.

**Is your feature request related to a problem? Please describe.**

I want to use the plugin's features when I create models dynamically. For example:

```python
from pydantic import BaseModel, create_model

DynamicFoobarModel = create_model('DynamicFoobarModel', foo=(str, ...), bar=123)


class StaticFoobarModel(BaseModel):
    foo: str
    bar: int = 123
```

**Describe the solution you'd like**

In the above example, I get autocompletion for `StaticFoobarModel`, but not for `DynamicFoobarModel`. Is there any way to get the plugin's features for `DynamicFoobarModel`?

More info about Pydantic dynamic models creation: https://pydantic-docs.helpmanual.io/usage/models/#dynamic-model-creation

Best,
Dario

**Comment by koxudaxi** [comment]
@bukosabino 
Thank you for the great suggestion.
It looks good :+1: 

OK, I try to implement the feature :rocket:

**Comment by koxudaxi** [comment]
@bukosabino 
I have started to implement this feature:rocket: 
But, I need time to complete the work. :nerd_face: 

![Screenshot_2020-08-18_05-35-34](https://user-images.githubusercontent.com/630670/90442809-343a7d80-e116-11ea-89de-44363a6b5078.png)
![Screenshot_2020-08-18_05-35-22](https://user-images.githubusercontent.com/630670/90442813-356baa80-e116-11ea-8769-d67109dd6c38.png)

**Comment by bukosabino** [comment]
Hi @koxudaxi ,

Thank you for your help.

Sorry, I can not help you with this task, because of the code language is not Python :(

Note: Jupyter Lab shows the autocompletion for the dynamic model.

![dynamic_autocompletation](https://user-images.githubusercontent.com/4375209/91010999-cd203b80-e5e3-11ea-930c-55ad8d4884e7.png)

Best,
Dario

**Comment by koxudaxi** [comment]
Interesting!! 
I will check the code of Jupyter :nerd_face: 

I have to implement different from `BaseModel` to support `dynamic_model()`
This problem comes from PyCharm.

**Comment by koxudaxi** [comment]
I close this issue Because I implemented the minimum features.

If a lot of users need more features, then I will re-open this one or create a new issue.
