### ISSUE TITLE
pycharm treats @validator decorated method as non-static method

### ISSUE THREAD

**Issue by no-life** [koxudaxi/pydantic-pycharm-plugin#195]
![image](https://user-images.githubusercontent.com/52041095/93813352-ab09ef80-fc5b-11ea-8379-95653c22ab0d.png)

The bar parameter shouldn't be treated this way.

PyCharm Pro 2020.2.2.
Pydantic plugin 0.1.13

**Comment by koxudaxi** [comment]
@no-life 
The first argument always is a class object.
It means the method is class method.
https://pydantic-docs.helpmanual.io/usage/validators/

**Comment by no-life** [comment]
It's work with class method, but PyCharm still warning
![image](https://user-images.githubusercontent.com/52041095/93822853-81f05b80-fc69-11ea-9ffe-3cc4a19673c9.png)

**Comment by koxudaxi** [comment]
I can't representation the error. I use the same versions.
![Screenshot_2020-09-22_16-20-57](https://user-images.githubusercontent.com/630670/93854675-249fed00-fcf1-11ea-9796-ac1dfbf5747c.png)

**Comment by no-life** [comment]
Are you have enabled this inspection
![image](https://user-images.githubusercontent.com/52041095/93879099-cf111380-fce3-11ea-9811-e64cffc40e13.png)

**Comment by no-life** [comment]
I found.
I have this warning if I import `from pydantic.class_validators import validator`.
But have no warning in this case `from pydantic import validator`.

**Comment by koxudaxi** [comment]
I understand the problem.
I will fix it.
Thank you :smiley:

**Comment by koxudaxi** [comment]
@no-life 
I have released a new version as `0.1.14`
![Screenshot_2020-09-23_02-56-46](https://user-images.githubusercontent.com/630670/93919354-88093980-fd48-11ea-86e4-e94afa70aba1.png)

**Comment by no-life** [comment]
Checked!
