### ISSUE TITLE
Code completion for custom descriptors on class level

### ISSUE THREAD

**Issue by rbolkhovitin** [koxudaxi/pydantic-pycharm-plugin#214]
**Describe the bug**
Code completion for custom descriptors doesn't work on class level.

**To Reproduce**

You could use this code snippet to reproduce behavior:

```python
import pydantic

class Descriptor:
    def __get__(self, instance, owner):
        return owner

class DummyModel(pydantic.BaseModel):
    id: int = 0

    class Config:
        keep_untouched = (Descriptor,)

    descriptor = Descriptor()

if __name__ == "__main__":
    item = DummyModel()
    assert item.id == 0
    assert item.descriptor == DummyModel
    assert "descriptor" not in item.dict()
```

**Expected behavior**
Custom descriptor presents in code completion when user types `DummyModel.d...`

**Screenshots**
![descriptor](https://user-images.githubusercontent.com/62013217/98361586-dd6d8180-203c-11eb-98fa-d94c5a3ddd90.gif)

**Environments:**
 - IDE: PyCharm 2020.2.3 Professional Edition
 - OS: Ubuntu 20.04.1 LTS
 - Pydantic Version: 1.6.1
 - Plugin version: 0.1.16

**Comment by koxudaxi** [comment]
@rbolkhovitin 
Thank you for creating this issue.

I understand why the plugin doesn't show a descriptor in code completion.
The plugin doesn't treat `Config.keep_untouched`.
I have to implement a feature to detect this config parameter.

I will try it. 
Thanks.

**Comment by rbolkhovitin** [comment]
Thank you for quick response and update!
