### ISSUE TITLE
Models with custom root types show problem

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#226]
**Describe the bug**
Using a model with a [custom root type](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) makes PyCharm show a warning when instantiating such a model.

**To Reproduce**

```
from typing import List

from pydantic import BaseModel


class StorageAmountsDB(BaseModel):
    """StorageAmounts model (db)"""
    __root__: List = []


def test_root_type():
    StorageAmountsDB(__root__=[1])

```

**Expected behavior**
It is no problem to provide a `__root__` argument.

**Screenshots**
<img width="527" alt="Bildschirmfoto 2020-12-14 um 4 16 58 PM" src="https://user-images.githubusercontent.com/7534547/102098870-f7626700-3e27-11eb-95a9-82b3edabeaab.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2020.3
 - OS: macOS  10.14
 - Pydantic Version: 1.7.3
 - Plugin version: 0.1.17

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
Thank you for creating this issue.
Oh, I'm sorry. It's a bug. I removed the private attribute from the suggestion.
But, I forget that I must exclude `__root__`.  I will fix it.

**Comment by chbndrhnns** [comment]
it seems that can be closes as there is a fixed merged already, am I correct?

**Comment by koxudaxi** [comment]
I'm sorry. 
I forgot to tell you it had released.

Yes, you are correct.
I closed it. Thank you.
