### ISSUE TITLE
`@validate_arguments` with `typing.NoReturn`: "got no return"

### ISSUE THREAD

**Issue by gertvdijk** [koxudaxi/pydantic-pycharm-plugin#243]
Whenever I'm using the [`@validate_arguments`](https://pydantic-docs.helpmanual.io/usage/validation_decorator/) decorator on a function that has a [`typing.NoReturn`](https://docs.python.org/3/library/typing.html#typing.NoReturn) return type, PyCharm complains `Expected to return Optional[Any], got no return`.

Changing the return type to `None` solves it. Not sure if it is related to Pydantic itself or the PyCharm plugin.

**Describe the solution you'd like**
First of all, ensure what piece is responsible for this. Validation errors are not triggered by Pydantic, so it's a clue it may be this PyCharm plugin, or perhaps how they interact.

**Describe alternatives you've considered**
I've considered filing this as a bug report to Pydantic, but not sure where the problem is exactly, not even if this is a feature request or a bug tbh.

**Additional context**
Using Python 3.8.0, PyCharm 2020.3.3, Pydantic 1.7.3 and the plugin 0.1.19.
![Screenshot_20210220_122330](https://user-images.githubusercontent.com/1550527/108593839-85058a00-7376-11eb-99f3-a49603fdd014.png)

**Comment by koxudaxi** [comment]
Thank you for creating this issue.

I guess this issue doesn't depend on Pydantic.
PyCharm shows the warning.
I write an example without pydantic.

```python3
from typing import Any, Callable, NoReturn


def deco(func: Callable[..., Any]) -> Callable[..., NoReturn]:
    def inner(*args) -> NoReturn:
        func(*args)
        raise Exception('error')
    return inner


@deco
def return_none(input_dict: dict) -> NoReturn:
    input_dict.update({"foo": "bar"})
    return None


@deco
def without_return(input_dict: dict) -> NoReturn:
    input_dict.update({"foo": "bar"})


@deco
def throw_exception() -> NoReturn:
    raise Exception('error')

```
<img width="732" alt="スクリーンショット 2021-02-21 0 16 34" src="https://user-images.githubusercontent.com/630670/108600340-178b4500-73da-11eb-9606-fa96e2103f21.png">


```
$  mypy models.py                                                                        
models.py:14: error: Return statement in function which does not return
models.py:18: error: Implicit return in function which does not return
Found 2 errors in 1 file (checked 1 source file)
```

I don't know why PyCharm shows the warning for only `without_return()`.
But, mypy don't accept other case exclude `throw_exception()`
If you want to know the detail of behavior then you should ask the issue to the PyCharm developer team.

**Comment by gertvdijk** [comment]
Thanks for the reply!

With this insight I agree that this seems unrelated to Pydantic or the PyCharm-Pydantic plugin, or at least pending a fix in PyCharm, then.

I guess this issue can be closed here.
