### ISSUE TITLE
Pydantic dataclass subclass names flagged as warning by inspection

### ISSUE THREAD

**Issue by cslominski** [koxudaxi/pydantic-pycharm-plugin#267]
In PyCharm 2021.1, which just became the version in Ubuntu, and Pydantic Plugin 0.2.1, the names of pydantic Dataclass subclasses seem to be lost in the code reference, leading to these kind of inspection warnings:

@pydantic.dataclasses.dataclass
class MyDataclass:
    pass

def my_fn() -> MyDataclass:
    return MyDataclass()

"Expected type 'MyDataclass', got 'Dataclass' instead"

I don't see these in Jupyter Notebooks, but I do see them in .py files.

Additionally, if I Ctrl+B (Go To Declaration or Usages) on the MyDataclass instantiation, it takes me to pydantic/dataclasses.py and not my definition. This behavior I see in both Notebooks and .py files.

Thanks!
Charlie

**Comment by koxudaxi** [comment]
@cslominski 
Thank you for creating this issue.
I can reproduce this problem with pydantic 1.7.
The problem doesn't happen with pydantic 1.6.
pydantic had changed the implementation for type-checking.

OK, I will fix it.

**Comment by cslominski** [comment]
Thanks @koxudaxi

**Comment by koxudaxi** [comment]
Also, The problem doesn't happen in PyCharm 2020.3 🤔

**Comment by koxudaxi** [comment]
@cslominski 
I have released a fixed version as `0.3.0`
Would you please check it?

**Comment by koxudaxi** [comment]
### Details of the problem
1. PyCharm 2021.1 detects types of decorators. PyCharm 2020.3 doesn't work the feature.
2. `@pydantic.dataclasses.dataclass` returns `Dataclass` as stub type. the type is in since pydantic version 1.7

The problem happened to combine 1. and 2.
I fixed the problem by ignoring `Dataclass`.
