### ISSUE TITLE
Improve BaseModel Completion

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#27]
## Detail
we should add CompletionContributor to improve  BaseModel Completion

## Related Links
https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/completion_contributor.html

**Comment by dmontagu** [comment]
Are there any specific capabilities this would add beyond what is currently implemented? Or is it just a "better" way to implement the same things?

**Comment by koxudaxi** [comment]
@dmontagu 
I thought we can use _the feature_ to improve completion ability. but, _the feature_ provide only the same thing. I knew it by researching _the feature_  yesterday.
