### ISSUE TITLE
Generic type is not offered for auto-complete

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#275]
**Describe the bug**
When using `GenericModel`, the parametrized type is not offered in the auto-completion.

**To Reproduce**
Take the snippet.

```py
from typing import TypeVar, Generic

from pydantic import UUID4
from pydantic.generics import GenericModel

IdT = TypeVar("IdT")


class BaseEntity(GenericModel, Generic[IdT]):
    id: IdT


class MyEntity(BaseEntity[UUID4]):
    ...


MyEntity(id=)

```

**Expected behavior**
I see `UUID4` as the expected type.

**Screenshots**
Also, gif movies are recommended.

<img width="418" alt="Screenshot 2021-04-15 at 12 19 51" src="https://user-images.githubusercontent.com/7534547/114854455-23492580-9de5-11eb-9e94-89de8c15fcd1.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2021.1
 - OS: macOS  11.1
 - Pydantic Version : 1.7.3 
 - Plugin version: 0.2.1

**Additional context**

**Comment by koxudaxi** [comment]
Thank you for creating this issue.
It may not easy to solve this problem.
But, I will try it.

**Comment by koxudaxi** [comment]
@chbndrhnns 
I'm sorry for my late.
New version 0.3.1 supports GenericModel!!

**Comment by chbndrhnns** [comment]
That's awesome! I will try it out soon!
