### ISSUE TITLE
Feature Request: Refactor from `__init__` signature updates model names.

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#29]
# Feature Request

In response to #16, it is now the case that refactors for class attributes result in a dialog offering the ability to change the variable names in `__init__` calls. This is **extremely useful**, and it is now possible in theory to do safe `__init__`-call refactors by just modifying the attribute name on the class.

However, it would still be nice to be able to perform the refactor operation directly from inside the `__init__` call, and have it update the class variable name *and* other `__init__` call keyword arguments.

This is a substantially lower priority since you can accomplish this now by just jumping to the class definition first and refactoring there, but I wanted to create an issue for tracking.

**Comment by koxudaxi** [comment]
@dmontagu 
I have implement you want the features. 
Would you please check the latest version on GitHub release page?
There is the plugin in JetBrains repo, but the version is a bit old.
The plugin is uploaded to JetBrains repo from CI.
However, Jetbrains member has to approve the plugin which to publish every version.
They spend two days for checking it :(

**Comment by dmontagu** [comment]
Amazing 🙌🎉🚀
