### ISSUE TITLE
PyCharm incorrectly reports the usage of `metaclass` and `Config` as an error.

### ISSUE THREAD

**Issue by TCampmany** [koxudaxi/pydantic-pycharm-plugin#296]
**Describe the bug**
PyCharm incorrectly reports the usage of `metaclass` and `Config` as an error.

**To Reproduce**
Create a file with the following content:
```python
import abc

from pydantic import BaseModel


class MyBaseModel(BaseModel, metaclass=abc.ABCMeta):
    class Config:
        validate_all = True
        validate_assignment = True
        underscore_attrs_are_private = False
```

PyCharm reports this structure as an error, see the screenshot.

**Expected behavior**
The plugin could have the same behaviour as the `ModelMetaclass` - which filters the keywords based on `allowed_config_kwargs`:
```python
        allowed_config_kwargs: SetStr = {
            key
            for key in dir(config)
            if not (key.startswith('__') and key.endswith('__'))  # skip dunder methods and attributes
        }
        config_kwargs = {key: kwargs.pop(key) for key in kwargs.keys() & allowed_config_kwargs}
        config_from_namespace = namespace.get('Config')
        if config_kwargs and config_from_namespace:
            raise TypeError('Specifying config in two places is ambiguous, use either Config attribute or class kwargs')

```

**Screenshots**
![image](https://user-images.githubusercontent.com/4998080/117987751-1283c500-b33b-11eb-8c20-5d1ec33e6c40.png)

**Environments:**
 - IDE: PyCharm 2021.1.1 (Professional Edition)
 - OS: macOS  11.3.1
 - Pydantic Version 1.8.2
 - Plugin version 0.3.1

**Comment by koxudaxi** [comment]
@TCampmany 
Thank you for creating this issue.
I have fixed the bug.
I will release it soon :rocket:

**Comment by koxudaxi** [comment]
@TCampmany 
The new version `0.3.2` has been released :tada: 
Would you please check it?

**Comment by TCampmany** [comment]
@koxudaxi 
Thanks, it is working flawlessly now!
