### ISSUE TITLE
Completion by alias might lead to syntax errors

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#300]
**Describe the bug**
Completion by alias might lead to syntax errors

**To Reproduce**
The offered completion would produce `object-megabytes` which is a syntax error.

**Expected behavior**
Not sure here. Can we indicate that the 'allow_population_by_field_name` is REQUIRED to be set for 
such a model?

**Screenshots**
<img width="685" alt="Screenshot 2021-05-18 at 09 13 50" src="https://user-images.githubusercontent.com/7534547/118608032-8c8fd000-b7b9-11eb-8dca-3d2d37846ee5.png">

**Environments (please complete the following information):**

 - IDE: PyCharm Pro 2021.1
 - OS: macOS  11.3.1
 - Pydantic Version: 1.7.4
 - Plugin version: 0.3.2

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
Thank you for creating this issue.
I have confirmed the problem.

> Not sure here. Can we indicate that the 'allow_population_by_field_name` is REQUIRED to be set for
> such a model?

OK, I will think about how to resolve this problem.

**Comment by koxudaxi** [comment]
@joniumGit 
Thank you for posting the error.
OK, I will fix the error this weekend :)

**Comment by koxudaxi** [comment]
@chbndrhnns @joniumGit 
The new version `0.3.3` has been released that is fixed the problem :tada:
