### ISSUE TITLE
Default value by variable for Field is not recognized

### ISSUE THREAD

**Issue by spacemanspiff2007** [koxudaxi/pydantic-pycharm-plugin#318]
**Describe the bug**
Default parameter for field that is passed by variable is not recognized

**To Reproduce**
```python
from typing import Final

from pydantic import BaseModel, Field

VERSION: Final = 1


class MyModel(BaseModel):
    version = Field(VERSION, const=True)


MyModel()
```
![grafik](https://user-images.githubusercontent.com/10754716/122550150-a2501980-d033-11eb-9024-ac123c1434d5.png)

**Expected behavior**
If I pass 1 directly it works as desired and no warning is shown.

**Environments (please complete the following information):**
- PyCharm 2021.1.2 (Community Edition)
- Plugin 0.3.3
- pydantic 1.8.2

**Comment by koxudaxi** [comment]
@spacemanspiff2007 
Thank you for creating this issue.
I will fix it.

**Comment by koxudaxi** [comment]
I believe this problem is resolved.

**Comment by spacemanspiff2007** [comment]
Yes - thank you very much for the fix!
