### ISSUE TITLE
Missing warning for mutable default argument

### ISSUE THREAD

**Issue by podj** [koxudaxi/pydantic-pycharm-plugin#340]
NOTE: I don't mind taking this one.

**Describe the bug**
When assigning a deafult value for dataclasses, the variable must not be mutable.
This is a very bad practice. We can see the solution for it in the dataclasses' PEP (557): https://www.python.org/dev/peps/pep-0557/#mutable-default-values

Currently, PyCharm warns against using mutable default arguments for data classes.
We should do the same for pydantic models.

**To Reproduce**
```
from dataclasses import dataclass
from pydantic import BaseModel

@dataclass
class Student:
    addresses: List[str] = []  # PyCharm warns against using mutable object here

class Student(BaseModel):
    addresses: List[str] = []  # No warning at all

```

**Expected behavior**
We should mimic PyCharm's behavior for data classes and warn as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/47007854/126471847-d0d800c0-1f26-45ac-9b3d-0b427e6c47cd.png)

**Environments (please complete the following information):**
 - IDE: PyCharm Professional Edition 2021.1.1
 - OS: macOS BigSur
 - Pydantic Version 0.18.0
 - Plugin version 0.3.4

**Comment by koxudaxi** [comment]
@podj
Thank you for creating this issue.
Pydnatic BaseModel copies the list from the class when creating an instance. 
I guess the warning is not needed.

```python
from pydantic import BaseModel


class C(BaseModel):
    x = []
    def add(self, element):
        self.x.append(element)

o1 = C()
o2 = C()
o1.add(1)
o2.add(2)
print(o1)
 # x=[1]
print(o2)
 # x=[2]
assert o1 != o2
```

**Comment by podj** [comment]
> @podj
> 
> Thank you for creating this issue.
> 
> Pydnatic BaseModel copies the list from the class when creating an instance. 
> 
> I guess the warning is not needed.
> 
> 
> 
> ```python
> 
> from pydantic import BaseModel
> 
> 
> 
> 
> 
> class C(BaseModel):
> 
>     x = []
> 
>     def add(self, element):
> 
>         self.x.append(element)
> 
> 
> 
> o1 = C()
> 
> o2 = C()
> 
> o1.add(1)
> 
> o2.add(2)
> 
> print(o1)
> 
>  # x=[1]
> 
> print(o2)
> 
>  # x=[2]
> 
> assert o1 != o2
> 
> ```

Hi, thanks for replying!
I must say that it is very odd behavior.
In our examples we used lists. But what if we will use a custom object? Say, another BaseModel.

How can pydantic copy/paste it? Using deepcopy techniques? I think it's not a good practice. This is why we should use the factory technique so we will be able to control the constructing process.

Weird 🤔

**Comment by koxudaxi** [comment]
@podj 
> How can pydantic copy/paste it? Using deepcopy techniques? 

Yes, you can check this code for copying default value.
```python
    def get_default(self) -> Any:
        return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
```
https://github.com/samuelcolvin/pydantic/blob/4a54f393ad20ee91b51cd7a49ec46771ba4f8a18/pydantic/fields.py#L372-L373

```python
def smart_deepcopy(obj: Obj) -> Obj:
    """
    Return type as is for immutable built-in types
    Use obj.copy() for built-in empty collections
    Use copy.deepcopy() for non-empty collections and unknown objects
    """
```
https://github.com/samuelcolvin/pydantic/blob/4a54f393ad20ee91b51cd7a49ec46771ba4f8a18/pydantic/utils.py#L609-L614

I don't say here whether the behavior is the best.
But, I believe the plugin works for the pydantic very well.
