### ISSUE TITLE
__root__ behaviour and 

### ISSUE THREAD

**Issue by freeseacher** [koxudaxi/pydantic-pycharm-plugin#364]
I've got a model that looks like that 
```
class AnotherModel(BaseModel):
  name: str
  ...
class Response(BaseModel):
    __root__: List[AnotherModel]
```

i have that like in code `products_info: List[AnotherModel] = Response.parse_obj(response.json())`
but pycharm shows that line as error, but if i remove type declaration i've got an error after when referencing name from `products_info`
looks like that is weird, but i'm unsure

**Comment by koxudaxi** [comment]
@freeseacher 

`products_info: List[AnotherModel] = Response.parse_obj(response.json())`

`Response` is not the same as `List[AnotherModel]`

You should access the `__root__` attribute to get `List[AnotherModel]`
```python
from typing import List

from pydantic import BaseModel


class AnotherModel(BaseModel):
    name: str


class Response(BaseModel):
    __root__: List[AnotherModel]


response = Response.parse_obj([{'name': 'dog'}])
print(response)
# __root__=[AnotherModel(name='dog')]

assert isinstance(response.__root__, list)
assert isinstance(response.__root__[0], AnotherModel)

```

**Comment by freeseacher** [comment]
tnx
