### ISSUE TITLE
Non-idempotent computation involving `__add__`

### ISSUE THREAD

**Issue by aphedges** [koxudaxi/pydantic-pycharm-plugin#371]
**Describe the bug**

I noticed a logged error message in PyCharm.

**To Reproduce**

Unsure what triggered it, but see [pydantic_stack_trace.txt](https://github.com/koxudaxi/pydantic-pycharm-plugin/files/7172915/pydantic_stack_trace.txt) for the error I received.

**Expected behavior**

No error should have occurred.

**Environments:**
 - IDE: PyCharm 2021.2.1 (Professional Edition)
 - OS: macOS  10.15.7
 - Pydantic Version: Unclear, given that PyCharm doesn't say which window the error occurred in
 - Plugin version: 0.3.4

**Comment by koxudaxi** [comment]
@aphedges
Thank you for creating this issue.
> Plugin version: 0.3.4

0.3.7 may be resolved the problem. 
Would you please update it?

**Comment by aphedges** [comment]
@koxudaxi, after I reported this issue, I found out I was out-of-date and updated to the latest version. I have no clue what caused the error in the first place, though, so I have no way to test if it was fixed.

**Comment by koxudaxi** [comment]
@aphedges 
Thank you for your feedback.
I believe the problem is in the latest version. If we don't meet the same error for a while, I would like to close this issue.

**Comment by aphedges** [comment]
@koxudaxi, that is fine with me.

**Comment by aphedges** [comment]
I have not seen this error for a while since I updated the plugin version over two months ago, so I am closing this issue.
