### ISSUE TITLE
Overridden fields not replaced

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#4]
See screenshot. In general, overriding the type of an annotated field in a subclass doesn't affect it (though going from optional to non-optional is the only case of this that I use).

Not sure if this would be a hard fix or not, but figured I'd flag it. It looks like neither the dataclasses.dataclass or attr.dataclass decorator do this either, so maybe it's not possible in PyCharm anyway. (mypy does handle it as intended though...)

![Screen Shot 2019-08-08 at 12 39 52 AM](https://user-images.githubusercontent.com/35119617/62684180-ff2d1400-b974-11e9-9b7c-6a380f19368f.png)

**Comment by koxudaxi** [comment]
@dmontagu 
Thank you for your report
I just fixed the problem.
I upload version 0.0.3
<img width="551" alt="ss2019-08-08 22 51 07" src="https://user-images.githubusercontent.com/630670/62708913-48419e80-ba2f-11e9-90c6-7ce12d898ac8.png">
