### ISSUE TITLE
The latest version 0.39 pydantic is not compatiable with Intellj 2021.3

### ISSUE THREAD

**Issue by zhfkt** [koxudaxi/pydantic-pycharm-plugin#404]
**Describe the bug**
The latest version 0.39 of pydantic is not compatiable with Intellj 2021.3. Version 0.39 is only supported in Pycharm 2021.3. 

![image](https://user-images.githubusercontent.com/4969804/144895496-bdd520ab-81e0-4465-af75-6ff50421b163.png)

If I installed it in my Intellj, the following error will be reported:

![image](https://user-images.githubusercontent.com/4969804/144895763-07bbed53-a188-457d-ab97-30e02b964e44.png)

It is because the version of Pycharm 2021.3 is 213.5744.248 but version of Intellj 2021.3 is 213.5744.223

Pls review.

Thank you !

**Comment by koxudaxi** [comment]
@zhfkt  
I'm sorry. I forget to share the fixed release.
https://github.com/koxudaxi/pydantic-pycharm-plugin/releases/tag/0.3.10

Thank you
