### ISSUE TITLE
Typo in PyCharm plugin

### ISSUE THREAD

**Issue by peterochek** [koxudaxi/pydantic-pycharm-plugin#406]
**Typo in second field description.**

**Steps to reproduce the behavior:**
Open PyCharm 'Pydantic' plugin menu in options.

**Expected behavior:**
If enabled, raise aN error whenever a field is declared on a model without explicitly specifying its type.

**Environment:**
 - PyCharm Community 2021.3
 - Windows 11
 - Pydantic Version - latest
 - Plugin version - 0.3.9

**Screenshot**
![изображение](https://user-images.githubusercontent.com/71915791/145291589-0ae7715e-0c3f-43df-8a4f-c51d152eee58.png)

**Comment by koxudaxi** [comment]
@peterochek 
I'm sorry. I forget to share the fixed release.
https://github.com/koxudaxi/pydantic-pycharm-plugin/releases/tag/0.3.10

Thank you
