### ISSUE TITLE
Feature request: Treat `validator` as producing a classmethod

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#41]
If this is hard to fix, it's not a big deal, but it would be nice to reduce some of the warnings-clutter pycharm generates:

```python
from pydantic import BaseModel, validator


class Model(BaseModel):
    x: int

    @validator("x")
    def double_x(cls, v):
        return v * 2
```

![Screen Shot 2019-08-16 at 11 02 58 AM](https://user-images.githubusercontent.com/35119617/63188053-4a9a8e80-c015-11e9-955a-b924c389e448.png)

**Comment by koxudaxi** [comment]
The supported version is released.
but, Pycharm do auto-fill a first argument as `self`
We will fix to auto-fill the parameter to `cls`.

![Kapture 2019-08-21 at 0 51 05](https://user-images.githubusercontent.com/630670/63363067-e4639200-c3ad-11e9-8279-ce6b629a8654.gif)
