### ISSUE TITLE
Pycharm performs refactoring when pressing ESC to cancel it

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#419]
**Describe the bug**
Pycharm performs refactoring when pressing ESC to cancel it.

**To Reproduce**
- Select the username field
- Hit Shift+F6 to rename
- Enter "user_name", press Enter
- In the next dialog, press Escape

```
from pydantic import BaseModel


class Model(BaseModel):
    username: str

    @classmethod
    def from_username(cls, username):
        return cls(username=username)

```

**Expected behavior**
The renaming is not performed. Instead, the renaming is performed.

**Screenshots**
![Kapture 2022-01-06 at 11 42 43](https://user-images.githubusercontent.com/7534547/148522466-8e0045be-830d-41b3-9949-d8bdfe2285b4.gif)

**Environments (please complete the following information):**
 - IDE: 2021.3.1
 - OS: macOS 15.2
 - Pydantic Version: 1.8.2
 - Plugin version: 0.3.10

**Additional context**
First reported to Pycharm:
https://youtrack.jetbrains.com/issue/PY-52426#comment=27-5690492

**Comment by koxudaxi** [comment]
@chbndrhnns
Thank you for reporting the issue.
I will fix it.

**Comment by koxudaxi** [comment]
@chbndrhnns 
I'm sorry for my late reply.
I just checked the behavior.
I guess the problem come from PyCharm.
Because, I can reproduce same problem without Pydantic Plugin.

```python


class Parent:
    @classmethod
    def from_username(cls, user_name):
        pass


class Child(Parent):
    @classmethod
    def from_username(cls, username):
        pass

```
https://user-images.githubusercontent.com/630670/152648373-c5cbdd19-8ef2-4bd5-a520-e887da684b20.mov

**Comment by chbndrhnns** [comment]
This was also my first idea which is why I posted it to the Pycharm tracker first. I will let them know about that. Thanks!
