### ISSUE TITLE
Incorrect behavior when `__call__` is defined

### ISSUE THREAD

**Issue by PhilReinhold** [koxudaxi/pydantic-pycharm-plugin#453]
**Describe the bug**
Plugin does does not correctly infer signature of pydantic models with `__call__` method defined

**To Reproduce**
See screenshot. Plugin confuses the `__init__` signature with the `__call__` signature in the final line.

**Expected behavior**
There should be no error in the final line of the linked screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/1217560/157925779-4154409f-5098-4bcc-a3fb-6c98ea9927bd.png)

**Environments (please complete the following information):**
 - IDE: 2021.3.1 Professional
 - OS: macos 11.6.4
 - Pydantic Version 1.8.2
 - Plugin version 0.3.12

**Comment by koxudaxi** [comment]
@PhilReinhold  
I have released a new version [v0.4.0](https://github.com/koxudaxi/pydantic-pycharm-plugin/releases/tag/v0.4.0) in [the merket](https://plugins.jetbrains.com/plugin/12861-pydantic/versions/stable/300885)
The version supports `__call__`.
Thank you.
