### ISSUE TITLE
validator functions not recognized as classmethods for dataclasses

### ISSUE THREAD

**Issue by igorbga** [koxudaxi/pydantic-pycharm-plugin#466]
**Describe the bug**
If I use a @validator decorator in a Pydantic regular model Pycharm does not complain about first parameter being called "cls", but if instead I use a Pydantic dataclass it complains

**To Reproduce**

```
from pydantic.dataclasses import dataclass

@dataclass(frozen=True)
class MyValueObject:
    value: str

    @validator('value')
    def _value_validator(cls, value):
        return value

```

**Expected behavior**
I would expect it not to complain about "cls" as it already does for BaseModels

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2021.3.3 
 - OS: Ubuntu 18.03
 - Pydantic Version 1.9.0
 - Plugin version 0.3.12

**Comment by koxudaxi** [comment]
@igorbga 
I'm sorry for my too-late reply.
The fixed version has been released.
Thank you very much.
