### ISSUE TITLE
Rename refactoring on local variable also renames field if same name

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#484]
**Describe the bug**
```py
import pydantic

class PydanticClass(pydantic.BaseModel):
    cls_member = ""

    @classmethod
    def do(cls):
        cls_member = "abc"
        assert cls_member


class Class:
    cls_member = ""

    @classmethod
    def do(cls):
        cls_member = "abc"
        assert cls_member
```

**To Reproduce**

1. Put cursor on`PydanticClass.do.cls_member` 
2. rename to `other`
3. Field `cls_member` is also renamed

**Expected behavior**
Only the local variable is renamed

(For comparison, do the same with `Class`.)

**Environments (please complete the following information):**
- IDE: PyCharm Professional 2022.1
- OS: macOS 12.3.1
- Pydantic Version: 1.9.0
- Plugin version: 0.3.12

**Additional context**

**Comment by koxudaxi** [comment]
I have released the fixed version `v0.4.2`
Thank you very much!!
