### ISSUE TITLE
(🐞) Every time a new IDE is released, the plugin is downgraded to 0.3.4

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/pydantic-pycharm-plugin#520]
`0.3.4` is marked as supporting `211.6693.111+`. This causes it to be installed when a user updates their IDE to a version that the current release doesn't support.

Is there any action we can take regarding this? Perhaps the older versions could be removed from the plugin marketplace, or perhaps their version range could be updated somehow?

All of these old versions are installable on the latest IDEs, but are completely broken.
![image](https://user-images.githubusercontent.com/65446343/181397542-defaaee6-bc2c-47f5-8027-2fd20653c20c.png)

**Comment by KotlinIsland** [comment]
Caused #516

**Comment by AI-shm** [comment]
Hi, I'm one of the JetBrains Marketplace admins. I adjusted the compatibility range for all the plugin updates, so now the issue should be resolved. To avoid this in the future, I would advise setting the `until-build` in every plugin update to match only the compatible IDE versions and not just every future version.
