### ISSUE TITLE
"Unexpected argument" warning when using __class__ of model instance

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#529]
**Describe the bug**
PyCharm shows an "unexpected argument" warning for this snippet:

```python
class M(p.BaseModel):
    a: int = 1


def test_():
    assert M.__class__.parse_obj(a=2)
```

**To Reproduce**
1. Copy & paste the snippet

**Expected behavior**
The class of a model has the field so it should not show up as unexpected

**Screenshots**

**Environments (please complete the following information):**
 - IDE: PyCharm 2022.2
 - OS: macOS 12.5
 - Pydantic Version: 1.9.1
 - Plugin version: 0.3.13

**Additional context**

**Comment by koxudaxi** [comment]
I'm sorry for my too-late reply.
`parse_obj` expect only `obj` as an argument.
It is not a bug.
