### ISSUE TITLE
Add type and default value to popup of auto-completion

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#53]
I want to look a type and a default value on popup of auto-completion

If some don't like the idea then, Would you please tell me? 

## Motivation
PyCharm show Model's class name on popup of auto-completion

However, I don't feel good that a popup of auto-completion doesn't show type and default value. 

By the way, IntelliJ shows a type as default in Java/Kotlin

## ScreenShot
I upload the screenshot of an experimental version.
I must handle a few definition cases.
<img width="674" alt="ss2019-08-29 0 38 23" src="https://user-images.githubusercontent.com/630670/63873998-9f69dc00-c9fb-11e9-9a04-d31fbb138503.png">

**Comment by koxudaxi** [comment]
@dmontagu 
Thank you for your response 

I have found a method to get a formatted type-hint text in source code of PyCharm.

Also, The popup of fields can show type-hint text.
We don't need to check the class definition to verify field types.

<img width="590" alt="ss2019-08-29 20 48 32" src="https://user-images.githubusercontent.com/630670/63938333-84e93e80-ca9f-11e9-943b-9f7840491941.png">

**Comment by pauleveritt** [comment]
This is a very cool feature. I use it with regular dataclasses all the time. Thanks for doing the extra work for this, on top of all the other regular commits you are putting into this.

**Comment by koxudaxi** [comment]
@pauleveritt
Thank you, too. I'm happy 😄 

PyCharm doesn't show types and default values on auto-completion 
But, I feel great about the feature with java/kotlin in IntelliJ. 
https://github.com/koxudaxi/pydantic-pycharm-plugin/issues/53#issuecomment-526152650

I think that the feature should be implemented in PyCharm.
Did JetBrains have a schedule for implementing the feature for Python in PyCharm? 
Also, Is there any reason that anybody don't do that?

**Comment by pauleveritt** [comment]
I checked with the guy that did our dataclasses implementation, he said "Don't know any reason why we don't do that" and it's a good idea for a feature request. Of course, you'll be first. :)

Kudos on this idea, BTW.

**Comment by koxudaxi** [comment]
Thank you for asking the guy about the question.

I have understood how to implement the future.
I may suggest a pull request to IntelliJ when I have time.

But, I know the best way is that the guy implements the feature. 😃
