### ISSUE TITLE
Completion adds superfluous "=" to field name

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#580]
**Describe the bug**
The plugin produces a SyntaxError when completing field names.

```py
import pydantic

class M(pydantic.BaseModel):
    old_password: str ="abc"
    new_password: str = "abc"

def test_():
    assert M(oldnew_password="def")
```

**To Reproduce**
1. Put cursor after `old` in the last line
2. Ctrl+space 
3. Tab complete
4. Gives me `assert M(old_password=="def")`

**Expected behavior**

Not comparison, but assignment:

`assert M(old_password="def")`

**Screenshots**
<img width="671" alt="Screenshot 2022-11-09 at 19 38 56" src="https://user-images.githubusercontent.com/7534547/200914170-0d85929f-afad-42c7-945f-4c4634f95ad7.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2022.3 EAP 4
 - OS: macos 12.6
 - Pydantic Version: 1.10
 - Plugin version: 0.3.15

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns
Thank you for creating the issue.
The fixed version has been released.
