### ISSUE TITLE
Support 2023.1 EAP

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#632]
**Is your feature request related to a problem? Please describe.**
Support PyCharm 2023.1 EAP's

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
I have released a new version [v0.4.1-231](https://plugins.jetbrains.com/plugin/12861-pydantic/versions/stable/301018)
Thank you.
