### ISSUE TITLE
False positive: "class 'Model' accepts only keyword arguments"

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#668]
**Describe the bug**
Accessing `type(SomeModel)` produces a warning which I believe is not correct.

**To Reproduce**
```py
import pydantic

class Model(pydantic.BaseModel):
    url: str

    def bla(self):
        assert type(self)
```

See warnings

**Expected behavior**
No warning

**Screenshots**
<img width="526" alt="Screenshot 2023-03-02 at 16 14 00" src="https://user-images.githubusercontent.com/7534547/222469188-89894e3a-841a-40c8-a105-dcffab044b05.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2023.1 EAP 3
 - OS:macOS 13.2.1
 - Pydantic Version: 1.10.2
 - Plugin version: 0.4.1-231
 - 
**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
Thank you for your report.
The new version has a bug related to call expression. :thinking:
