### ISSUE TITLE
Does not look into `typing.Annotated` to find default

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#731]
**Describe the bug**
PyCharm complains about "Parameter 'field_one' unfilled" in the last line.

**To Reproduce**
```py
def test_():
    import pydantic
    import typing as t

    def random_value():
        return 0

    class M(pydantic.BaseModel):
        field_one: t.Annotated[
            str,
            Indexed(idx_name="my-index", unique=True),
            pydantic.Field(default_factory=random_value),
        ]

    assert M()

```

**Expected behavior**
PyCharm does not complain

**Screenshots**

**Environments (please complete the following information):**
 - IDE: PyCharm 2023.2 EAP 4
 - OS: macOS 13.4.1
 - Pydantic Version: 1.10.7
 - Plugin version: 0.4.3-232

**Additional context**

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/koxudaxi/pydantic-pycharm-plugin/issues/731">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/koxudaxi/pydantic-pycharm-plugin/issues/731/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/koxudaxi/pydantic-pycharm-plugin/issues/731/pledge.svg">
</picture>
</a>

**Comment by Tshimanga** [comment]
I have encountered this issue as well.
