### ISSUE TITLE
Ignore fields with leading "_"

### ISSUE THREAD

**Issue by skewty** [koxudaxi/pydantic-pycharm-plugin#77]
```py
import xmltodict, typing
from pydantic import BaseModel

Model = typing.TypeVar('Model', bound='HIPEventBase')

class HIPEventBase(BaseModel):
    __ROOT_TAG__ = "FOO"

    @classmethod
    def get_root_tag(cls) -> str:
        return cls.__ROOT_TAG__

    def xml(self) -> str:
        return xmltodict.unparse({self.__class__.get_root_tag(): self.dict(by_alias=True)})

    @classmethod
    def parse_xml(cls: typing.Type[Model], b: str) -> Model:
        # noinspection PyArgumentList
        return cls(**xmltodict.parse(b)[cls.get_root_tag()])

    x: int
    y: int
```

Please don't show `__ROOT_TAG__` as a field that needs to be populated in constructor.

I think it would also be expected that any field starting with '_' is ignored (perhaps check into implementation details in pydantic source).  I have verified that a leading `__` prevents pydantic from creating a "field".

**Comment by koxudaxi** [comment]
Sorry, I don't know the behavior.
I can ignore the filed easy.
I will create the PR.
Thank you.

**Comment by skewty** [comment]
It's merged so I will close this :)

**Comment by koxudaxi** [comment]
We should wait to approved for two business days
