### ISSUE TITLE
PydanticV2 Config Dict "populate_by_name" parameter ignored

### ISSUE THREAD

**Issue by Jan-Jasek** [koxudaxi/pydantic-pycharm-plugin#785]
**Describe the bug**
When defining Pydantic field with alias, populating model by field name lints Unexpected argument, even when Pydantic V2 ConfigDict `populate_by_name` parameter is set to `True`.

**To Reproduce**
Run this snippet in Pycharm with Pydantic plugin installed

```
class User(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str = Field(alias="full_name")


if __name__ == '__main__':
    print(User(name="John"))
```

**Expected behavior**
As defined per [documentation](https://docs.pydantic.dev/2.0/usage/model_config/#populate-by-name), with `populate_by_name=True` one should be able to create the model both using the alias and using the field name, so no linter error should be raised. With `populate_by_name=False`, the model should only be created using field alias.

**Screenshots**
<img width="665" alt="image" src="https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/42320929/ebb2f011-4a69-4fcc-8dd5-12f445152bf6">

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2023.2
 - OS: macOS  13.4.1
 - Pydantic Version: 2.1.1
 - Plugin version: 0.4.7

**Comment by shoarata** [comment]
Hi!
I'm still experiencing this issue with the latest version of the plugin, it does go away if I use the deprecated:

```python
class Config:
    allow_population_by_field_name = True
```

**Comment by pawrequest** [comment]
february 2025 and this is still an issue with Pycharm Pro (2024.3.2)

**Comment by pawrequest** [comment]
unless i'm doing something dumb the fix didnt work? maybe the new pycharm version broke your plugin fix?

<img width="1706" height="1253" alt="Image" src="https://github.com/user-attachments/assets/04ea4db1-dab1-4242-a0be-6dfe060f451f" />
