### ISSUE TITLE
not support autocomplete from  embed model, eg: ChatOpenAI

### ISSUE THREAD

**Issue by linpan** [koxudaxi/pydantic-pycharm-plugin#796]
from langchain.chat_models import ChatOpenAI

ChatOpenAI dont suport autocompelete.

`ChatOpenAI-> BaseMessageChunk->Serializable->BaseModel`

extra: 
pydantic: v2.3.0
Build #PY-232.9559.58, built on August 23, 2023
plugins: v0.4.7

<img width="754" alt="image" src="https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/6077601/c7d66218-2222-4a1a-bf91-569238dc999b">

<img width="682" alt="image" src="https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/6077601/557ab181-ba89-459e-82c6-39b5c1dbf438">

**Comment by koxudaxi** [comment]
@linpan 
Thank you for creating the issue.
I have related the new version `0.4.9`
The changes ignore __init__() arguments as default.
I quote the part of the document.

https://koxudaxi.github.io/pydantic-pycharm-plugin/ignore-init-arguments/
https://github.com/koxudaxi/pydantic-pycharm-plugin/pull/798
👇

**This feature is in version 0.4.9 or later**

If a third-party library provides a model that extends BaseModel, it may override the `__init__` method, as in `__init__(self, **kwargs)`.
If this is the case, the plugin user should set `ignore-init-method-arguments = true` to ignore the `__init__` method argument.
But it is difficult to tell if the library is using BaseModel or not.

The plugin ignore the `__init__` method if argument is only `**kwargs`. the option is provided as `ignore-init-method-keyword-arguments`.
This option is enabled by default, so if you create a model that inherits from BaseModel with a method like `__init__(self, **kwargs)` defined, ignore this `init` argument.

If you want to disable this option, please put the following setting in `pyproject.toml`.

```toml
[tool.pydantic-pycharm-plugin].
ignore-init-method-keyword-arguments = true
```

**Comment by linpan** [comment]
thks,  now is okay.  🚀
![image](https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/6077601/5360c074-cee2-4b51-8c12-c21c06bff996)
