### ISSUE TITLE
Instructions to build from source

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#8]
It looks like the intended way of installing this is to just directly "install from disk" the jar file you've included in the repo.

Is there any way you could include instructions for how to build the jar from source? I think this would alleviate some potential security concerns with installing the downloaded jar, since it is difficult to confirm it precisely reflects what is in the source.

I think if you add that, I think we might be able to convince samuelcolvin to add a link to this in the pydantic docs as the "unofficial pycharm plugin".

**Comment by koxudaxi** [comment]
> Is there any way you could include instructions for how to build the jar from source? I think this would alleviate some potential security concerns with installing the downloaded jar, since it is difficult to confirm it precisely reflects what is in the source.

I agree.
I build the plugin on IntelliJ  GUI. I don't know how to make it on CLI.
I will check how to build it on CI. And I put instructions.

> I think if you add that, I think we might be able to convince samuelcolvin to add a link to this in the pydantic docs as the "unofficial pycharm plugin".

Thank you for your good idea.
Also,  I want to publish the plugin on the jetbrains plugin repository.

**Comment by dmontagu** [comment]
@koxudaxi A CI/docker build would be great.

Alternatively, even just committing the .idea project, if that's less work!

**Comment by koxudaxi** [comment]
@dmontagu 
I added Gradle build script and write how to build it on `README`.
And, if I create a `tag` on git, then Travis-ci builds a plugin and put the plugin on Github's Release page as an asset.

**Comment by dmontagu** [comment]
I haven't confirmed it works for me locally yet, but I'll close the issue. If it doesn't work, I'll reopen. Thanks!!
