### ISSUE TITLE
False positive -- class 'Foo' accepts only keyword arguments

### ISSUE THREAD

**Issue by skewty** [koxudaxi/pydantic-pycharm-plugin#80]
```py
from typing import NamedTuple, Union, cast
from pydantic import BaseModel

class Foo(BaseModel):
    name: str

class Bar(BaseModel):
    index: int

FooBar = Union[Foo, Bar]
PendingEntry = NamedTuple('PendingEntry', [('payload', FooBar), ('expiry', float)])

request = cast(Bar, None)
# noinspection Pydantic
pending_entry = PendingEntry(request, 12.0)  # Pydantic plugin error: class 'Foo' accepts only keyword arguments
```

**Comment by koxudaxi** [comment]
Sorry, I can't replay the error.
Would you please show me a plugin version?

**Comment by dmontagu** [comment]
@koxudaxi I get the error if I delete the `# noinspection Pydantic` in the second-to-last line using version 0.0.21. (This appears to be the latest version that can be installed through pycharm directly.)

**Comment by koxudaxi** [comment]
Wow,  `# noinspection Pydantic` is special comment. I don't know the feature.

Thank you very much. I will fix it.

**Comment by skewty** [comment]
Changelog says this is fixed in newest version
