### ISSUE TITLE
Feature Request: Auto-completion for Config fields

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#83]
It would be great if we could see auto-completion choices for the model `Config` -- I always have to Cmd+Click through multiple layers of definitions to get to the declaration of `BaseConfig` before I can confirm the name of a `Config` attribute.

I have no idea how hard this would be since `Config` isn't declared to inherit from anything. But it would be awesome if it weren't too much work!

**Comment by koxudaxi** [comment]
It was published.
