### ISSUE TITLE
Attempting to use a non-existing model field is not detected as a problem in pydantic v2

### ISSUE THREAD

**Issue by oleg-rmd** [koxudaxi/pydantic-pycharm-plugin#851]
**Describe the bug**
Attempting to use a non-existing field does not get marked as a warning when using pydantic v2.

**To Reproduce**
1. Ensure "Python | Type checker compatible with Pydantic", "Python | Pydantic definition and usages", and "Python | Unresolved references" inspections are configured to level warning.

* NOTE: I also tried disabling them one at a time, and it did not make a difference.
* NOTE: There is no such inspection "Type Checker" any more, so I cannot disable it.

2. Create a python file with the following code.

```python
import dataclasses

from pydantic import BaseModel


@dataclasses.dataclass
class A:
    a: int = 1


class B(BaseModel):
    a: int = 1


a = A(a=1)
print(a.fake)

b = B(a=1)
print(b.fake)
```

**Actual behavior**
`a.fake` generates an unresolved reference warning, but `b.fake` does not show any warning.

**Expected behavior**
`b.fake` should be flagged as unresolved reference, non-existing attribute, or similar warning.

**Screenshots**
<img width="306" alt="image" src="https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/50600269/fc344e34-0c1b-488b-8445-0ee432e862ee">

**Environments (please complete the following information):**

 - IDE: PyCharm 2023.3.1 (Professional Edition)
 - OS: macOS 12.7.1
 - Pydantic Version 2.5.2
 - Python Version 3.12.1 (also tried with 3.9.x)
 - Plugin version 0.4.10

**Additional context**

Also reproduced on CLion Nova with the Python Community Edition plugin 233.13309

I also tried:
* Uninstalling and re-installing pydantic
* "Repair IDE" (all the way to Invalidate Caches and Restart)

Switching the import to `from pydantic.v1 import BaseModel` fixes the issue.

**Comment by koxudaxi** [comment]
@oleg-rmd 
Thank you for creating the PR. 
I agree with you.
I will fix it.
