### ISSUE TITLE
`HttpUrl` field works not as expected

### ISSUE THREAD

**Issue by Danipulok** [koxudaxi/pydantic-pycharm-plugin#869]
**Description**
`HttpUrl` field works not as expected

**To Reproduce**
1. Install pydantic (not tested on other versions):
```bash
pip install pydantic==1.10.12
````

2. Paste following code to the file
```python
from pydantic import BaseModel, HttpUrl

class Test(BaseModel):
    url: HttpUrl

test = Test(url="https://httpbin.org/get")
````

**Expected behavior**
Nothing must be lightened because pydantic auto handles when `str` passed to `HttpUrl` field.

**Actual behavior**
Plugin highlights `Test(url="https://httpbin.org/get")` with:
```
Expected type 'HttpUrl', got 'str' instead 
```

**Screenshots**
https://ibb.co/W6dSXHh

**Environments (please complete the following information):**
 - IDE: PyCharm 2023.3.3 (Professional Edition)
 - OS: Windows 10.0
 - Pydantic Version: 1.10.12
 - Plugin version: com.koxudaxi.pydantic (0.4.11)

**Comment by skewty** [comment]
I think this is working correctly. If you want auto-type conversion you should be using `BaseModel.model_validate()`.
