### ISSUE TITLE
Custom Fields not recognised by PyCharm

### ISSUE THREAD

**Issue by avlahop** [koxudaxi/pydantic-pycharm-plugin#87]
I have the following custom Field:

```python
class NonEmptyString(str):
     @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if v == "":
            raise ValueError("Non-empty string expected")
        return v
```

and a model using it:

```python
class MyModel(BaseModel):
    field: NonEmptyString
```

but when I instantiate `MyModel`:

```python
my_model = MyModel(field="a string")
```

I get the following warning from pycharm's linter:

`Expected type 'NonEmptyString' got 'str' instead`

Is this behaviour expected?

**Versions**
pydantic              1.1.1    
pycharm-pydantic-plugin: 0.0.27

**Comment by dmontagu** [comment]
I think this is expected; the only alternative would be to drop the type-checking for the `__init__` entirely.

This has been discussed before, but I think it makes sense to make this a plugin config setting. Alternatively, the `__init__` types could all be `Any`, and the plugin could generate a typed signature for `BaseModel.construct`, but that won't apply any of the validators, so anywhere you are using `__init__` for meaningful logic, you'd lose type hints.

@koxudaxi Maybe we could add a pycharm-plugin-specific config setting (wouldn't need to be an official part of pydantic at all) that would let you enable/disable a typed init on a model-by-model basis? Something like `pycharm_typed_init = False` (or `True`)?

**Comment by koxudaxi** [comment]
@avlahop 
> Is this behaviour expected?

Yes, We expect the behavior. 
@dmontagu explained about the behavior and history.

We should add a panel of settings to control the warnings.
Sorry, I have not tried to implement the feature yet.
I will try it next week.

@dmontagu 
Your idea looks good. But I try to implement the panel of settings.
If I can not do it next week, then let's discuss the option on `config.

**Comment by otsuka** [comment]
FYI, 
pydantic `EmailStr` has a bug.

`EmailStr` type is used in a model, 

```py
addr = Address(email='foo@example.com')
```

the plugin raises a warning on editor.

```py
addr = Address(email=EmailStr('foo@example.com'))
```
This code is type checking safe, but running it on Linux raises ValidationError.
https://github.com/samuelcolvin/pydantic/issues/1070#issuecomment-568477871

**Comment by koxudaxi** [comment]
@avlahop

I write a workaround.
I add a new type-checker in the plugin.
You can set parsable-type and acceptable-type. there are details in this [document page](https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/)

If you want to remove warning then, you should change `acceptable-type-highlight ` to `"disable"`


![Screenshot_2020-04-28_23-41-38](https://user-images.githubusercontent.com/630670/80501156-1059fd00-89aa-11ea-9ac9-ab48b5b6443f.png)


pyproject.toml:
```toml
[tool.pydantic-pycharm-plugin]
# You can select higlith level  from "warning",  "weak_warning", "disable"
parsable-type-highlight = "warning"
acceptable-type-highlight = "weak_warning"
[tool.pydantic-pycharm-plugin.acceptable-types]
"main.NonEmptyString" = ["str"]
```

**Comment by koxudaxi** [comment]
I think the workaround is good.
If someone would discuss the issue then, I will re-open the issue.
