### ISSUE TITLE
False positive UnionType - RootModel generic doesn't like union types

### ISSUE THREAD

**Issue by skewty** [koxudaxi/pydantic-pycharm-plugin#878]
![image](https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/9087223/82101330-b220-4ffb-a484-bab3363fba8d)

This is made further annoying when using your Ruff plugin as using `Optional[str]` also needs a `# noqa: UP007`.

Perhaps this is an upstream PyCharm bug?

**Comment by koxudaxi** [comment]
@skewty 
 I tested your code without the Pydnatic plugin. (PY-233.13763.11)
I guess the problem comes from the PyCharm side.
![image](https://github.com/koxudaxi/pydantic-pycharm-plugin/assets/630670/e2d8059d-8257-4959-8374-a9a4894e7c84)

**Comment by skewty** [comment]
https://youtrack.jetbrains.com/issue/PY-70544/False-positive-UnionType-not-accepted-but-Optional-is.
