### ISSUE TITLE
Unittest failed in  `241.13688.16-EAP-SNAPSHOT`

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/pydantic-pycharm-plugin#887]
**Describe the bug**
After `241.13688.16-EAP-SNAPSHOT`, unittest is failed.
We should fix it before release it.

https://github.com/koxudaxi/pydantic-pycharm-plugin/actions/runs/7994205495/job/21879373618

**Comment by koxudaxi** [comment]
@KotlinIsland 
> platformVersion = 241.13688.16-EAP-SNAPSHOT

Can you help me a little?
My work has been stuck on this problem for the past few days.
I believe 2024.1 will be released soon and I need to fix the problem as soon as possible.
Running unittest on the latest version of EAP almost always fails.
At least I don't think this plugin is taken into account during unittest. (debugging does not reach the breakpoint)

Do you have any idea what it is?

**Comment by KotlinIsland** [comment]
I can take a look

**Comment by KotlinIsland** [comment]
@koxudaxi I played around with it for a while, but I can't figure it out.
I agree, it appears that the plugin is not being loaded, I suspect it is related to the changes in `PythonMockSdk.create` from ddda1401

**Comment by koxudaxi** [comment]
@KotlinIsland 
Thank you for your time.
I checked the related code of MockSdk and project fixtures.
But, They didn't change last month 🤔 

Yes, I followed the changes.
https://github.com/JetBrains/intellij-community/blob/master/python/testSrc/com/jetbrains/python/PythonMockSdk.java

**Comment by KotlinIsland** [comment]
Ah yes... what do you think about specifying an older EAP that works properly then? Perhaps it's an issue with the EAP?

**Comment by koxudaxi** [comment]
> Ah yes... what do you think about specifying an older EAP that works properly then? Perhaps it's an issue with the EAP?

If it is one previous EAP, it will work.
The remedy is to release it once specifying the previous EAP version.
However, the unit test will not be able to be cleared in the new version in the future.
The API around typing changes rapidly with version upgrades, so unittest is a must.

If it is a bug in the latest EAP, it is fine 😢

**Comment by koxudaxi** [comment]
@KotlinIsland 
Since we can't take time for this task, how about we set the unittest execution environment to 2023.3 for once?
I tested it at hand, and it works with 241-EPA (without unittest).
For now, we've released the 241-EAP version.

**Comment by koxudaxi** [comment]
We have no time, so we have turned off unittest and released it.
We will need to investigate again as unittest will be required in future versions.
