### ISSUE TITLE
Bug: Field names treated with incorrect scope

### ISSUE THREAD

**Issue by dmontagu** [koxudaxi/pydantic-pycharm-plugin#89]
If you create a local variable in a method with the same name as a field, you get strange behavior from PyCharm. In particular, it seems to consider the field a local variable inside the method.

Note the difference in behavior in the following two screenshots when the class is a subclass of `BaseModel` vs. not:

![Screen Shot 2019-11-26 at 1 12 08 PM](https://user-images.githubusercontent.com/35119617/69673155-92867400-104e-11ea-8888-417f4ac46b3b.png)
![Screen Shot 2019-11-26 at 1 09 58 PM](https://user-images.githubusercontent.com/35119617/69673160-96b29180-104e-11ea-993e-da10f021b316.png)

**Comment by koxudaxi** [comment]
It was fixed
