### ISSUE TITLE
Do not warn on `__system__` style fields without type specification

### ISSUE THREAD

**Issue by skewty** [koxudaxi/pydantic-pycharm-plugin#94]
Given:

```py
import pydantic
class Foo(pydantic.BaseModel):
    __special_value__ = 12
    count: int
    bar: str
```

pydantic leaves `__special_value__` as a class variable and doesn't try to interpret it.

The plugin should also allow this and not warn that it requires a type.

**Comment by koxudaxi** [comment]
Sorry, I took so late to reply.

OK, I will fix it.

**Comment by koxudaxi** [comment]
Sorry,  I had failed to publish the version.  
I have pushed again. It will be able to download after a few days.
