### ISSUE TITLE
Prepare for 2024.2

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#961]
We have EAP releases already, would it be possible to make the tool ready for 2024.2?

**Comment by koxudaxi** [comment]
Sorry, I've been busy.
The necessary changes are tested here.
Perhaps we can support it if you don't use utility classes for conda, for example.
https://github.com/koxudaxi/ruff-pycharm-plugin/pull/461

**Comment by chbndrhnns** [comment]
I'll be happy without conda but can only speak for myself.
